workflows:
  depannage-build:
    name: Build Depannage APK
    environment:
      flutter: stable
    scripts:
      - name: Get dependencies
        script: flutter pub get
        working_directory: mobile
      - name: Build APK
        script: flutter build apk --release --android-skip-build-dependency-validation
        working_directory: mobile
    artifacts:
      - mobile/build/app/outputs/flutter-apk/app-release.apk
