workflows:
  depannage-build:
    name: Build Depannage APK
    environment:
      flutter: stable
    scripts:
      - flutter pub get
      - flutter pub run flutter_launcher_icons
      - flutter build apk --release --android-skip-build-dependency-validation
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
