workflows:
  depannage-build:
    name: Build Depannage APK
    environment:
      flutter: stable
    scripts:
      - name: Get dependencies
        working_directory: mobile
        script: flutter pub get
      - name: Generate icons
        working_directory: mobile
        script: flutter pub run flutter_launcher_icons
      - name: Build APK
        working_directory: mobile
        script: flutter build apk --release --android-skip-build-dependency-validation
    artifacts:
      - mobile/build/app/outputs/flutter-apk/app-release.apk
