import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;
  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static final Map<String, Map<String, String>> _translations = {
    'ar': {
      'app_name': 'ديباناج',
      'tow_service': 'خدمة الجر بين يديك',
      'search_hint': 'ما الوجهة وما التكلفة؟',
      'request_tow': 'طلب ونش',
      'choose_vehicle': 'اختر نوع المركبة',
      'motorcycle': 'دراجة',
      'car': 'سيارة سياحية',
      'utility': 'سيارة نفعية',
      'light_truck': 'شاحنة خفيفة',
      'heavy_truck': 'شاحنة ثقيلة',
      'price': 'السعر',
      'suggested_price': 'السعر المقترح',
      'publish_request': 'نشر الطلب للسائقين القريبين',
      'offers': 'عروض السائقين',
      'accept_offer': 'قبول العرض',
      'waiting_offers': 'جاري البحث عن سائقين قريبين...',
      'tracking': 'تتبع الونش',
      'cash_payment': 'الدفع نقداً حصراً للسائق عند الوصول',
      'final_amount': 'المبلغ النهائي',
      'complete_ride': 'إنهاء الرحلة',
      'rating': 'التقييم',
      'send_rating': 'إرسال التقييم',
      'history': 'سجل الطلبات',
      'settings': 'الإعدادات',
      'profile': 'الملف الشخصي',
      'logout': 'تسجيل الخروج',
      'logout_confirm': 'هل تريد حقاً تسجيل الخروج؟',
      'language': 'اللغة',
      'dark_mode': 'الوضع الداكن',
      'driver_mode': 'وضع شريك العمل',
      'workshops': 'ورشات التصليح',
      'call': 'اتصال',
      'directions': 'توجيه',
      'driver_onboarding': 'طلب الشراكة للسائقين',
      'full_name': 'الاسم الكامل',
      'phone': 'رقم الهاتف',
      'license_number': 'رقم رخصة القيادة',
      'license_expiry': 'تاريخ صلاحية الرخصة',
      'plate_number': 'رقم لوحة السطحة',
      'vehicle_type': 'نوع السطحة',
      'year': 'سنة الصنع',
      'upload_docs': 'رفع الوثائق',
      'license_front': 'رخصة القيادة (الأمام)',
      'license_back': 'رخصة القيادة (الخلف)',
      'insurance': 'وثيقة التأمين',
      'id_document': 'بطاقة الهوية / السجل التجاري',
      'vehicle_photo': 'صورة السطحة',
      'terms': 'الشروط والأحكام',
      'agree_terms': 'أوافق على الشروط والأحكام',
      'submit_request': 'إرسال طلب الشراكة',
      'pending_state': 'تم إرسال طلبك بنجاح، جاري مراجعة الوثائق من قبل الإدارة',
      'completed': 'مكتملة',
      'cancelled': 'ملغية',
      'call_support': 'الاتصال بالدعم الفني',
      'about_app': 'حول التطبيق',
      'contact_whatsapp': 'اتصل بنا عبر واتساب',
      'version': 'الإصدار',
      'save': 'حفظ',
      'cancel': 'إلغاء',
      'confirm': 'تأكيد',
      'reorder': 'إعادة الطلب',
      'no_history': 'لا توجد طلبات سابقة',
      'no_workshops': 'لا توجد ورشات شراكة متاحة حالياً',
    },
    'fr': {
      'app_name': 'Dépannage',
      'tow_service': 'Service de remorquage entre vos mains',
      'search_hint': 'Quelle destination et quel coût ?',
      'request_tow': 'Demander une dépanneuse',
      'choose_vehicle': 'Choisir le type de véhicule',
      'motorcycle': 'Moto',
      'car': 'Voiture de tourisme',
      'utility': 'Véhicule utilitaire',
      'light_truck': 'Camion léger',
      'heavy_truck': 'Camion lourd',
      'price': 'Prix',
      'suggested_price': 'Prix suggéré',
      'publish_request': 'Publier la demande aux conducteurs proches',
      'offers': 'Offres des conducteurs',
      'accept_offer': 'Accepter l\'offre',
      'waiting_offers': 'Recherche de conducteurs à proximité...',
      'tracking': 'Suivi de la dépanneuse',
      'cash_payment': 'Paiement en espèces uniquement au chauffeur à l\'arrivée',
      'final_amount': 'Montant final',
      'complete_ride': 'Terminer la course',
      'rating': 'Évaluation',
      'send_rating': 'Envoyer l\'évaluation',
      'history': 'Historique des demandes',
      'settings': 'Paramètres',
      'profile': 'Profil',
      'logout': 'Déconnexion',
      'logout_confirm': 'Voulez-vous vraiment vous déconnecter ?',
      'language': 'Langue',
      'dark_mode': 'Mode sombre',
      'driver_mode': 'Mode partenaire',
      'workshops': 'Ateliers de réparation',
      'call': 'Appeler',
      'directions': 'Itinéraire',
      'driver_onboarding': 'Demande de partenariat',
      'full_name': 'Nom complet',
      'phone': 'Téléphone',
      'license_number': 'Numéro de permis',
      'license_expiry': 'Expiration du permis',
      'plate_number': 'Immatriculation',
      'vehicle_type': 'Type de véhicule',
      'year': 'Année',
      'upload_docs': 'Télécharger les documents',
      'license_front': 'Permis (recto)',
      'license_back': 'Permis (verso)',
      'insurance': 'Assurance',
      'id_document': 'Carte d\'identité / Registre de commerce',
      'vehicle_photo': 'Photo du véhicule',
      'terms': 'Conditions générales',
      'agree_terms': 'J\'accepte les conditions',
      'submit_request': 'Envoyer la demande',
      'pending_state': 'Votre demande a été envoyée avec succès, en attente de validation',
      'completed': 'Terminée',
      'cancelled': 'Annulée',
      'call_support': 'Contacter le support',
      'about_app': 'À propos',
      'contact_whatsapp': 'Contactez-nous via WhatsApp',
      'version': 'Version',
      'save': 'Enregistrer',
      'cancel': 'Annuler',
      'confirm': 'Confirmer',
      'reorder': 'Commander à nouveau',
      'no_history': 'Aucune demande précédente',
      'no_workshops': 'Aucun atelier partenaire disponible',
    },
    'en': {
      'app_name': 'Depannage',
      'tow_service': 'Towing service in your hands',
      'search_hint': 'What destination and what cost?',
      'request_tow': 'Request a tow',
      'choose_vehicle': 'Select vehicle type',
      'motorcycle': 'Motorcycle',
      'car': 'Passenger car',
      'utility': 'Utility vehicle',
      'light_truck': 'Light truck',
      'heavy_truck': 'Heavy truck',
      'price': 'Price',
      'suggested_price': 'Suggested price',
      'publish_request': 'Publish request to nearby drivers',
      'offers': 'Driver offers',
      'accept_offer': 'Accept offer',
      'waiting_offers': 'Searching for nearby drivers...',
      'tracking': 'Track tow truck',
      'cash_payment': 'Cash only payment to the driver upon arrival',
      'final_amount': 'Final amount',
      'complete_ride': 'Complete trip',
      'rating': 'Rating',
      'send_rating': 'Submit rating',
      'history': 'Trip history',
      'settings': 'Settings',
      'profile': 'Profile',
      'logout': 'Logout',
      'logout_confirm': 'Are you sure you want to logout?',
      'language': 'Language',
      'dark_mode': 'Dark mode',
      'driver_mode': 'Partner mode',
      'workshops': 'Repair workshops',
      'call': 'Call',
      'directions': 'Directions',
      'driver_onboarding': 'Driver partnership request',
      'full_name': 'Full name',
      'phone': 'Phone',
      'license_number': 'License number',
      'license_expiry': 'License expiry',
      'plate_number': 'Plate number',
      'vehicle_type': 'Vehicle type',
      'year': 'Year',
      'upload_docs': 'Upload documents',
      'license_front': 'License (front)',
      'license_back': 'License (back)',
      'insurance': 'Insurance',
      'id_document': 'ID / Commercial register',
      'vehicle_photo': 'Vehicle photo',
      'terms': 'Terms & Conditions',
      'agree_terms': 'I agree to terms and conditions',
      'submit_request': 'Submit partnership request',
      'pending_state': 'Your request has been sent successfully, pending review',
      'completed': 'Completed',
      'cancelled': 'Cancelled',
      'call_support': 'Contact support',
      'about_app': 'About app',
      'contact_whatsapp': 'Contact us via WhatsApp',
      'version': 'Version',
      'save': 'Save',
      'cancel': 'Cancel',
      'confirm': 'Confirm',
      'reorder': 'Reorder',
      'no_history': 'No previous requests',
      'no_workshops': 'No partner workshops available',
    },
  };

  String? translate(String key) {
    return _translations[locale.languageCode]?[key] ??
        _translations['ar']![key] ??
        key;
  }
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['ar', 'fr', 'en'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
